### ISSUE TITLE
Feature Request: Firewall/restricting access to certain IPs

### ISSUE THREAD

**Issue by bryceadams** [ptrofimov/beanstalk_console#139]
This would be a nice addition :)

**Comment by pentium10** [comment]
I don't think that a PHP application should have any Infrastructure feature. Thus there are so many Operating Systems each with their own firewall services, this cannot be done.

Also since also the rest of the services needs to be Firewall protected this needs to go into the Firewall service and not into a library.

**Comment by bryceadams** [comment]
Good point - I was thinking the same as I posted. Thanks!
