### ISSUE TITLE
Understanding the interface

### ISSUE THREAD

**Issue by MarkVaughn** [ptrofimov/beanstalk_console#82]
I am not sure where to find support for this, please check this image of my console
![beanstalk](https://cloud.githubusercontent.com/assets/39970/6397426/990e179a-bdb2-11e4-9df7-14052dcb649f.png)

I'm not sure what the total-jobs column means? First I thought it was completed jobs but reading your tooltip
"*cumulative count of jobs created in this tube __in the current beanstalkd process__*"
 sounds like I have 400+ jobs in memory hung up in some sort of infinity state? how can I see the  jobs "in the process"

also is current using + current watching mean there are 5 processes trying to work through this?

**Comment by pentium10** [comment]
total-jobs as the protocol says is how many jobs were on that tube since beanstalkd server is up (not your script).

you don't have any jobs to process, and total is just a stat value so those messages are not in memory.

- "current-using" is the number of open connections that are currently
   using this tube.

 - "current-waiting" is the number of open connections that have issued a
   reserve command while watching this tube but not yet received a response.

 - "current-watching" is the number of open connections that are currently
   watching this tube.

you can ask support questions on stackoverflow, make sure you tag the question with beanstalkd 

http://stackoverflow.com/questions/tagged/beanstalkd

**Comment by MarkVaughn** [comment]
thanks for clarifying, so I have 5 connections to beanstalkd right (3+2)?

**Comment by pentium10** [comment]
you have 3 connections
