### ISSUE TITLE
refresh in tube view

### ISSUE THREAD

**Issue by thinkerytim** [ptrofimov/beanstalk_console#97]
The view showing a specific tube doesn't appear to refresh the count as the main "tubes" page does. Is this as designed, and if so are there plans to implement the auto-refresh in the tube view?
Thanks

**Comment by pentium10** [comment]
Refresh was not designed for the current tube view. Mainly because you have two sections on that page. One is the table with totals, the other is the next job section with job details.
When turning on auto-refresh totals could be updated, but the next job is kinda hard and has a strong performance hit on the server to peek for jobs details each time. Thus if the tube has active workers peeking to next job, always will be out of scope as that job will be quickly reserved and executed by a worker.
On the other hand we didn't see any practical benefit having this auto-refresh on the current tube view. What are your thoughts?
